name: Release

on:
  push:
    branches: [ "master" ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Release
        uses: go-semantic-release/action@v1
        env:
          github-token: ${{ secrets.TAG_TOKEN }}
